### ISSUE TITLE
[RESEARCH] Address Component

### ISSUE THREAD

**Issue by ajeetd** [MetaMask/snaps#2609]
Research requirements

- Limitations of current component
- Add support for BTC or others
- #metamask-account-snaps

**Comment by david0xd** [comment]
Given that scope of work and targeted outcome of it, is not very clear at the moment, I identified few series of questions to be answered in order to identify goals and specify tasks.

Input from designer is required, to determine complete UX/UI expectations.

To be answered:
- Input
    - What type of Input we want to support?
        - Selection of address
        - Arbitrary address input
    - Which blockchain addresses we want to support (only ETH and BTC for now, or more in start?)
    - Do we want to have validation for address display and inputs?
        - If yes, for which blockchains
- Display
    - Do we want separate copyable component or displaying addresses for other blockchains?
        - Do we need a component-level validation for displaying addresses?
- Component mapping
    - To which extension components we want to map our SnapUI address input?
    - Do we have available components which we can map and use?
        - If yes, are available components suitable for the purpose of BTC or other blockchain addresses?
        - If no, how do we approach this requirement?
            - Build components ourselves?
            - Ask other team to build or modify existing?
- Special functionalities and handling
    - Do we need BTC (or other blockchain) addresses stored in the Address Book?
        - If yes, does this already work for other addresses?
        - If no, how do we handle and build that?
- Additional thoughts and comments
    - Do we want to target BTC address support only in the beginning or we want to build something more generic, multichain, at the beginning?

Questions are relatively based on the provided design for BTC flow presented in Figma: https://www.figma.com/design/2cqqTWJKoHcjYVGfNXxLbQ/Beyond-Ethereum?node-id=1268-8117&t=OdAYPMuy6COLOo4N-0

**Comment by david0xd** [comment]
This task is considered as done and actionable items are followed up and discussed in several series of meetings and other tasks related to the Address component within BTC flow work.
