### ISSUE TITLE
Allow snaps to link to a companion DApp

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#550]
A team we have been talking to suggested that we allow snaps to link to their optional companion DApp in the MetaMask UI. This would make sure that users are using a non-malicious companion DApp for snaps that currently require one.

**Comment by rekmarks** [comment]
We don't have a good place to put this kind of content right now, so this is in a sense blocked by https://github.com/MetaMask/metamask-extension/issues/14976.

That said, we could add a field to the manifest and expose it in settings. @FrederikBolding if you want to drive this we should discuss it async to think through the security implications, otherwise we can icebox this for now.

**Comment by Montoya** [comment]
This will be solved by #20988
